apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: eprst
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: eprst
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
