apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: web-canary1
spec:
  rules:
    - host: nginx.local
      http:
        paths:
        - path: /canary/
          pathType: Prefix
          backend:
            service:
              name: web-svc-canary1
              port:
                number: 80


