apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-canary1
spec:
  rules:
    - http:
        paths:
        - path: /canary
          backend:
            serviceName: web-svc-canary1
            servicePort: 80


