---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-csi-hostpath
provisioner: hostpath.csi.k8s.io
volumeBindingMode: Immediate 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi
spec:
  storageClassName: sc-csi-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-pod
    image: alpine
    volumeMounts:
    - name: data
      mountPath: "/data"
    command: ["/bin/sh"]
    args: ["-c","sleep 500000"]
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-csi
