---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-csi-hostpath
provisioner: hostpath.csi.k8s.io
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi
spec:
  storageClassName: sc-csi-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
  - name: nginx-storage
    image: nginx:stable
    volumeMounts:
    - name: data
      mountPath: "/data"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: storage-pvc

