apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: 
  - "get"
  - "watch"
  - "list"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-binding
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: sa-list
  apiGroup: rbac.authorization.k8s.io

