apiVersion: v1
kind: Service
metadata:
  labels: 
    nameapp: nginx-exporter
  name: nginx-exporter-svc
  #namespace: monitoring
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: nginx-exporter 
      protocol: TCP
      port: 9113
      targetPort: 9113
