apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-harbor
  namespace: harbor
spec:
  secretName: tls-secret-harbor
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "harbor.35.224.184.62.nip.io"
  dnsNames: 
  - "harbor.35.224.184.62.nip.io"
