apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  names:
    kind: MySQL
    plural: mysqls
    shortNames:
    - ms
    singular: mysql
  scope: Namespaced
  versions:
  - name: v1
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                type: string
            type: object
          spec:
            properties:
              database:
                type: string
              image:
                type: string
              password:
                type: string
              storage_size:
                type: string
            required:
            - image
            - database
            - password
            - storage_size
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        type: object
    served: true
    storage: true

